title:             Seemingly Wise Ramblings
email:             nathan.parker.williams001@gmail.com
description:       The ramblings and adventures of a young nerdy guy.
author:            Nathan Parker Williams
url:               "http://natethesage.github.io"
permalink:         /blogs/:year/:month/:day/:title 

# Social Profiles
github_username:   NateTheSage

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
